### ISSUE TITLE
'Payment' object has no attribute 'order'

### ISSUE THREAD

**Issue by Dufran** [jazzband/django-payments#353]
Trying to follow example app for stripe implementation. Installed django-paymetns==2.0.0
After a successful card check, I receive error 
'Payment' object has no attribute 'order' it seems that `clean` method in stripe form trying to access `order` attribute that are not present. 
https://github.com/jazzband/django-payments/blob/ae18fa09aa0fb197d0ac746c87d67aaeb8ad7b26/payments/stripe/forms.py#L47
Is there any way to make this work on 2.0.0?

**Comment by WhyNotHugo** [comment]
This was fixed in https://github.com/jazzband/django-payments/pull/349

**Comment by Dufran** [comment]
Many thanks for referencing issue. But is there any way for this yo work on v2.0.0 that are distributed on Pypi?

**Comment by WhyNotHugo** [comment]
If you want to hack around the issue, you can add an `order` property to your payment model and make sure that whatever this property returns has a `get_metadata` method. This won't break on 2.1.0.

Right now a new release is blocked mostly because I need an approval to merge https://github.com/jazzband/django-payments/pull/348.

**Comment by Dufran** [comment]
Many thanks, for clarification
